defaults:
  - _self_
  - dataset: train
  - model: stp_gsr

experiment:
  n_epochs: 30
  batch_size: 16

  lr: 0.005
  log_val_loss: False                   # Indicates whether to log validation loss every epoch. Could be resource intensive

  base_dir: 'results'
  run_name: 'run4'

  kfold:
    n_splits: 3
    shuffle: True
    random_state: 42

